### ISSUE TITLE
Script for VSRL Agents not working

### ISSUE THREAD

**Issue by dmelichar** [IBM/vsrl-framework#5]
I am trying to use the framework, but unfortunately the provided scripts do not work. I'm not sure if this is an issue on my end, or if it may be because of unspecified dependency versions. I would be really happy for some help.

# Expected Behavior

Running the `scripts/train_rl.py` should work. The error I get is the following.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/6791298/97911710-05629980-1d4c-11eb-8214-a6f8a26a93e7.png">

# Possible Solution

Add a `requirements.txt` file

# Steps to Reproduce

As stated in the README.

``` bash
python scripts/train_rl.py --env_name ACC --pbar true
```

P.S. it is required to specify the pbar parameter as true/false. The README does not state that.

# Context (Environment)

Branch - master
Commit hash - 93d85dd
Environment - macOS

<details>
<summary>
Package Versions
</summary>

- absl-py==0.11.0
- attrs==20.2.0
- auto-argparse==0.0.7
- cachetools==4.1.1
- certifi==2020.6.20
- chardet==3.0.4
- cloudpickle==1.6.0
- comet-ml==3.2.5
- configobj==5.0.6
- cycler==0.10.0
- dataclasses==0.6
- dulwich==0.20.6
- everett==1.0.3
- fsspec==0.8.4
- future==0.18.2
- google-auth==1.22.1
- google-auth-oauthlib==0.4.1
- grpcio==1.33.1
- gym==0.17.3
- idna==2.10
- jsonschema==3.2.0
- kiwisolver==1.3.0
- Markdown==3.3.3
- matplotlib==3.3.2
- netifaces==0.10.9
- numpy==1.19.2
- nvidia-ml-py3==7.352.0
- oauthlib==3.1.0
- opencv-python==4.4.0.44
- parsimonious==0.8.1
- Pillow==8.0.1
- portion==2.1.3
- protobuf==3.13.0
- psutil==5.7.3
- pyasn1==0.4.8
- pyasn1-modules==0.2.8
- pyglet==1.5.0
- pyparsing==2.4.7
- pyrsistent==0.17.3
- python-dateutil==2.8.1
- pytorch-lightning==1.0.4
- PyYAML==5.3.1
- requests==2.24.0
- requests-oauthlib==1.3.0
- rlpyt @ git+https://github.com/astooke/rlpyt.git@f04f23db1eb7b5915d88401fca67869968a07a37
- rsa==4.6
- scipy==1.5.3
- six==1.15.0
- sortedcontainers==2.2.2
- tensorboard==2.3.0
- tensorboard-plugin-wit==1.7.0
- toml==0.10.1
- torch==1.7.0
- torchvision==0.8.1
- tqdm==4.51.0
- typing-extensions==3.7.4.3
- urllib3==1.25.11
- websocket-client==0.57.0
- Werkzeug==1.0.1
- wrapt==1.12.1
- wurlitzer==2.0.1

</details>

**Comment by nrfulton** [comment]
This should be fixed by b1508cc, but please let me know if you run into any issues. 

In the new year we'll add some tests to ensure that all provided examples run properly, as well as a Dockerfile. Sorry for the delay, and thanks for taking the time to file this issue!
